### ISSUE TITLE
Add isLocal argument to fromJsDate method of Datetime

### ISSUE THREAD

**Issue by esuca** [archimedes-projects/archimedes-js#7]
Sometimes we want to transform a JavaScript Date to our Datetime wrapper **AND keep the local time zone**.

The time zone is always UTC in the current implementation:
```ts
  static fromJsDate(date: Date) {
    return new Datetime(LuxonDatetime.fromJSDate(date))
  }
```
Because the Datetime constructor already supports the isLocal argument, I think the following implementation change is the more accurate:
```ts
  static fromJsDate(date: Date, isLocal: boolean = false) {
    return new Datetime(LuxonDatetime.fromJSDate(date), isLocal)
  }
```

**Comment by cesalberca** [comment]
Maybe the second parameter should be an object in order to support more options in the future. Will that suffice @esuca?

**Comment by cesalberca** [comment]
This will be released in v2!
